### ISSUE TITLE
es语法转换问题。

### ISSUE THREAD

**Issue by DukeeXiao** [xfy520/v3-color-picker#1]
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| function on(element, event, handler) {
|   if (element && event && handler) {
>     element?.addEventListener(event, handler, false);
|   }
| }

引用依赖后报了以上的错误，插件打包时能否对高版本es语法进行转换？

**Comment by kissIce** [comment]
我也遇到了相同的问题，想问下你是怎么解决的？
